### ISSUE TITLE
add: del-cli

### ISSUE THREAD

**Issue by LyssenkoAlex** [abyss-soft/webpack#1]
Добрый день!
При попытке запуска команды npm run build получил ошибку del-cli is not recognized.
Добавьте пожалуйста ваш замечательный проект 
"del-cli": "^3.0.0",
в devDependencies.
Спасибо!

**Comment by abyss-soft** [comment]
Добрый день!
Спасибо за дополнение. 
"del-cli": "^3.0.0" добавлен.
